# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('raw_content', models.TextField(blank=True)),
                ('background', models.TextField(default='/static/img/post-bg.jpg')),
                ('vote', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
