# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='background',
            field=models.TextField(null=True),
        ),
    ]
