# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170419_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='background',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
